### ISSUE TITLE
Improvement of AbstractInterval

### ISSUE THREAD

**Issue by natir** [rust-bio/rust-bio-types#1]
Hi,

I think this crate is a very good idea.

But now AbstractInterval is clearly built for only genome concerned, so it could be more generic.

First replace contig by sequence, isn't very important but it is not very important but all the intervals do not concern only the contigs.
I would also like to replace the str type by a generic type that implement Index for a Range which would allow the user to use the data structure he wants.

I propose something like this : 
```rust
pub type Position = usize;

pub trait AbstractInterval<I: Index<Range<Position>>> {

    /// Identifier for a genomic contig, e.g., a chromosome
    fn sequence(&self) -> &I;
    
    /// Interval on the contig
    fn range(&self) -> Range<Position>;

    fn subsequence(&self) -> &<I as Index<Range<Position>>>::Output; 
}
    
    
pub struct Interval<I: Index<Range<Position>>> {
    sequence: I,
    range: Range<Position>,
}

impl AbstractInterval<String> for Interval<String> {

    fn sequence(&self) -> &String {
        &self.sequence
    }

    fn range(&self) -> Range<Position> {
        self.range.clone()
    }
    
    fn subsequence(&self) -> &str {
        return &self.sequence[..][self.range.clone()];
    }
}
```

Thank

**Comment by johanneskoester** [comment]
The contig thing is meant as a name for the sequence though, not the sequence itself. E.g. to represent `chr1:1-5000`. I guess that we should rename it to `sequence_name` instead of `contig`

**Comment by natir** [comment]
Okay I understand why Intervals is in the genomic crates.

Do you think my version of Intervals, which can be renamed SubcribalIntervals has a place in rust-bio-types?

**Comment by johanneskoester** [comment]
Yes, I think so. It is always easier to plan something like that if you have a concrete use case. Can you provide something?

**Comment by natir** [comment]
Hi,

Sorry I forget this issue :)

A concrete use case of SubscribalIntervals can be usefull for manage intervals on DNA sequence.

For example to extract a subpart of a FastqRecord with automatic set header and sequence and quality field.

**Comment by johanneskoester** [comment]
Ok, great! Thanks a lot for the suggestion. The API looks good! Do you plan a PR?

**Comment by natir** [comment]
Ok, thanks

I can do a PR during next week.

I close this issue.
