### ISSUE TITLE
Genome annotations

### ISSUE THREAD

**Issue by ingolia** [rust-bio/rust-bio-types#5]
A while ago, I put together a set of data types to represent genomic annotations or regions -- I had a few key features, which included the need to keep track of strand information some of the time, and the ability to track a "spliced" genomic location (in the sense of pre-mRNA splicing).

Briefly, it features a few different location types -- single positions, contiguous locations, and spliced locations -- as well as a general location trait. They're generic over the type of the chromosome name (so you could use String, an interned Rc<String>, or an i32 target ID from a BAM file) and over the strandedness (some annotations may be stranded while others aren't, and this provides a type-level guarantee to separate this). They also feature some useful interval math, e.g., given a position and an annotation, find the offset of the position in the annotated feature.

I was revisiting some of this recently and made a quick attempt to add this as a module in rust-bio-types. [Here is this annot module](https://github.com/ingolia/rust-bio-types/tree/annot/src/annot). Would something of this general design be interesting, in this crate, or in the rust-bio crate?

**Comment by johanneskoester** [comment]
Absolutely, it would be great to include this in rust-bio-types! I am looking forward to a PR!
